# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage:$(imageName)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'BlazorPasswordGenerator.sln'
    feedsToUse: 'select'
  displayName: 'Restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'BlazorPasswordGeneratorTest/BlazorPasswordGeneratorTest.csproj'
    arguments: '--collect "Code coverage"'
  displayName: 'Test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release -o $(Build.SourcesDirectory)/out'
  displayName: 'Publish'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/out'
    Contents: 'BlazorPasswordGenerator.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  displayName: 'Copy files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
